# Generated by Django 5.2.6 on 2025-10-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dish",
            options={
                "ordering": ["name"],
                "verbose_name": "dish",
                "verbose_name_plural": "dishes",
            },
        ),
        migrations.AlterField(
            model_name="dishtype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
